addSbtPlugin("io.get-coursier"   % "sbt-coursier"         % "1.0.0-RC10")
addSbtPlugin("net.vonbuchholtz"  % "sbt-dependency-check" % "0.1.10")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-license-report"   % "1.2.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"        % "1.5.0")
addSbtPlugin("com.orrsella"      % "sbt-stats"            % "1.0.5")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"          % "0.3.1")
